steps:
- name: 'gcr.io/cloud-builders/gcloud'
  id: Update rambutan server
  entrypoint: /bin/sh
  args:
  - '-c'
  - |
    set -x && \
    gcloud compute ssh billsgate-frontend --zone=asia-east1-a --command='/bin/sh /home/kevinyu05062006/deploy.sh'