version: '3.1'

services:
  nginx:
    build: ./nginx
    container_name: billsgate-frontend-nginx
    ports:
      - 80:80
    restart: always

  frontend:
    build: ./frontend
    container_name: billsgate-frontend
    restart: always
    expose:
      - 8080
